In [1]:
#Kariveda Trisha
#Bl.EN.U4CSE21091

In [2]:
import math
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [3]:
df = pd.read_csv("Skin_Cancer_Metadata.csv")
df

lesion_id      image_id     dx dx_type   age     sex localization
0      HAM_0000118  ISIC_0027419    bkl   histo  80.0    male        scalp
1      HAM_0000118  ISIC_0025030    bkl   histo  80.0    male        scalp
2      HAM_0002730  ISIC_0026769    bkl   histo  80.0    male        scalp
3      HAM_0002730  ISIC_0025661    bkl   histo  80.0    male        scalp
4      HAM_0001466  ISIC_0031633    bkl   histo  75.0    male          ear
...            ...           ...    ...     ...   ...     ...          ...
10010  HAM_0002867  ISIC_0033084  akiec   histo  40.0    male      abdomen
10011  HAM_0002867  ISIC_0033550  akiec   histo  40.0    male      abdomen
10012  HAM_0002867  ISIC_0033536  akiec   histo  40.0    male      abdomen
10013  HAM_0000239  ISIC_0032854  akiec   histo  80.0    male         face
10014  HAM_0003521  ISIC_0032258    mel   histo  70.0  female         back

[10015 rows x 7 columns]

In [4]:
missing_val= df['age'].mean()
df['age'].fillna(missing_val, inplace = True)

In [5]:
label_encoder = LabelEncoder()
df['dx'] = label_encoder.fit_transform(df['dx'])
df.to_csv('encoded_skin_cancer.csv', index=False)

In [6]:
df = pd.read_csv("encoded_skin_cancer.csv")
df

lesion_id      image_id  dx dx_type   age     sex localization
0      HAM_0000118  ISIC_0027419   2   histo  80.0    male        scalp
1      HAM_0000118  ISIC_0025030   2   histo  80.0    male        scalp
2      HAM_0002730  ISIC_0026769   2   histo  80.0    male        scalp
3      HAM_0002730  ISIC_0025661   2   histo  80.0    male        scalp
4      HAM_0001466  ISIC_0031633   2   histo  75.0    male          ear
...            ...           ...  ..     ...   ...     ...          ...
10010  HAM_0002867  ISIC_0033084   0   histo  40.0    male      abdomen
10011  HAM_0002867  ISIC_0033550   0   histo  40.0    male      abdomen
10012  HAM_0002867  ISIC_0033536   0   histo  40.0    male      abdomen
10013  HAM_0000239  ISIC_0032854   0   histo  80.0    male         face
10014  HAM_0003521  ISIC_0032258   4   histo  70.0  female         back

[10015 rows x 7 columns]

In [10]:
df['dx_type'] = label_encoder.fit_transform(df['dx_type'])
df['age'] = label_encoder.fit_transform(df['age'])
df['sex'] = label_encoder.fit_transform(df['sex'])
df['localization'] = label_encoder.fit_transform(df['localization'])
df.to_csv('encoded_skin_cancer.csv', index=False)

In [11]:
df = pd.read_csv("encoded_skin_cancer.csv")
df

lesion_id      image_id  dx  dx_type  age  sex  localization
0      HAM_0000118  ISIC_0027419   2        3   17    1            11
1      HAM_0000118  ISIC_0025030   2        3   17    1            11
2      HAM_0002730  ISIC_0026769   2        3   17    1            11
3      HAM_0002730  ISIC_0025661   2        3   17    1            11
4      HAM_0001466  ISIC_0031633   2        3   16    1             4
...            ...           ...  ..      ...  ...  ...           ...
10010  HAM_0002867  ISIC_0033084   0        3    8    1             0
10011  HAM_0002867  ISIC_0033550   0        3    8    1             0
10012  HAM_0002867  ISIC_0033536   0        3    8    1             0
10013  HAM_0000239  ISIC_0032854   0        3   17    1             5
10014  HAM_0003521  ISIC_0032258   4        3   15    0             2

[10015 rows x 7 columns]

In [9]:
#A1. Train a support vector machine using the training set

In [17]:
dx1 = 4
dx2 = 5

twoclass_dataset = df[df['dx'].isin([dx1, dx2])]

X = twoclass_dataset[['age','sex','localization']]
y = twoclass_dataset['dx']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

# SVM model
clf = SVC(kernel='linear')
clf.fit(X_train, y_train)

support_vectors = clf.support_vectors_

print("The Number of support vectors are:", len(support_vectors))
print("Support Vectors are:\n", support_vectors)


The Number of support vectors are: 1809
Support Vectors are:
 [[13.  1.  2.]
 [10.  1.  2.]
 [10.  0.  9.]
 ...
 [14.  0.  2.]
 [18.  1. 13.]
 [13.  1.  0.]]


In [ ]:
#A2.Test the accuracy of the SVM.

In [18]:
clf.score(X_test, y_test)

0.8471867007672634

In [ ]:
#A3. Use the Predict function of SVC classifier.

In [21]:
from sklearn.metrics import accuracy_score
y_pred = clf.predict(X_test)
accuracy_clf = accuracy_score(y_test, y_pred)
print("Accuracy is:", accuracy_clf)

Accuracy is: 0.8471867007672634


In [22]:
clf.predict(X_test)

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [ ]:
#A4. Experiment with various kernel functions (‘linear’, ‘poly’, ‘rbf’ & ‘sigmoid’)

In [35]:
#poly kernal
clf_1 = SVC(kernel='poly')
clf_1.fit(X_train, y_train)

support_vectors = clf_1.support_vectors_

print("The Number of support vectors in poly kernal:", len(support_vectors))
print("Support Vectors:\n", support_vectors)

The Number of support vectors in poly kernal: 1847
Support Vectors:
 [[13.  1.  2.]
 [10.  1.  2.]
 [10.  0.  9.]
 ...
 [14.  0.  2.]
 [18.  1. 13.]
 [13.  1.  0.]]


In [36]:
y_pred = clf_1.predict(X_test)
accuracy_poly = accuracy_score(y_test, y_pred)
print("Accuracy of poly kernal is:", accuracy_poly)

Accuracy of poly kernal is: 0.8471867007672634


In [42]:
#rbf kernal
clf_2 = SVC(kernel='rbf')
clf_2.fit(X_train, y_train)

support_vectors = clf_2.support_vectors_

print("The Number of support vectors in rbf kernal:", len(support_vectors))
print("Support Vectors are:\n", support_vectors)

The Number of support vectors in rbf kernal: 1877
Support Vectors are:
 [[13.  1.  2.]
 [10.  1.  2.]
 [10.  0.  9.]
 ...
 [13.  0.  6.]
 [14.  0.  2.]
 [18.  1. 13.]]


In [43]:
y_pred = clf_2.predict(X_test)
accuracy_rbf = accuracy_score(y_test, y_pred)
print("Accuracy of rbf kernal is:", accuracy_rbf)

Accuracy of rbf kernal is: 0.8471867007672634


In [44]:
#sigmoid kernal
clf_3 = SVC(kernel='sigmoid')
clf_3.fit(X_train, y_train)

support_vectors = clf_3.support_vectors_

print("The Number of support vectors in sigmoid kernal:", len(support_vectors))
print("Support Vectors are:\n", support_vectors)

The Number of support vectors in sigmoid kernal: 1216
Support Vectors are:
 [[13.  1.  2.]
 [10.  1.  2.]
 [10.  0.  9.]
 ...
 [12.  1. 14.]
 [14.  1.  9.]
 [18.  1. 13.]]


In [46]:
y_pred = clf_3.predict(X_test)
accuracy_sigmoid = accuracy_score(y_test, y_pred)
print("Accuracy of sigmoid kernal is:", accuracy_sigmoid)

Accuracy of sigmoid kernal is: 0.8005115089514067


In [47]:
print("Accuracies of all kernals are:")
print("Accuracy of linear kernal is:", accuracy_clf)
print("Accuracy of poly kernal is:", accuracy_poly)
print("Accuracy of rbf kernal is:", accuracy_rbf)
print("Accuracy of sigmoid kernal is:", accuracy_sigmoid)

Accuracies of all kernals are:
Accuracy of linear kernal is: 0.8471867007672634
Accuracy of poly kernal is: 0.8471867007672634
Accuracy of rbf kernal is: 0.8471867007672634
Accuracy of sigmoid kernal is: 0.8005115089514067
